version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-176-34-114-78.eu-west-1.compute.amazonaws.com
            database: dfm7njqompn05g
            schema: public
            user: zzlimvlciyrewy
            password: 30a9432304a3447eed27d516dc7e01c8a9fc0c7cb145f2893d0000343c4b3464
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true